// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmqtzMCrhAG7yCayniNBxeDG6SozWF-aE',
    appId: '1:496642683774:web:8e608751847217c473392f',
    messagingSenderId: '496642683774',
    projectId: 'paganini-15f75',
    authDomain: 'paganini-15f75.firebaseapp.com',
    databaseURL: 'https://paganini-15f75-default-rtdb.firebaseio.com',
    storageBucket: 'paganini-15f75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWJYDPBOILxC_vX_gsnq20tocutpPuFfs',
    appId: '1:496642683774:android:0f192bab9f227b3d73392f',
    messagingSenderId: '496642683774',
    projectId: 'paganini-15f75',
    databaseURL: 'https://paganini-15f75-default-rtdb.firebaseio.com',
    storageBucket: 'paganini-15f75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmmkOiXL9EF9hGGj97tg-gAYpbvk7UYJM',
    appId: '1:496642683774:ios:6b1f6409d4fdab3273392f',
    messagingSenderId: '496642683774',
    projectId: 'paganini-15f75',
    databaseURL: 'https://paganini-15f75-default-rtdb.firebaseio.com',
    storageBucket: 'paganini-15f75.firebasestorage.app',
    iosBundleId: 'com.example.paganini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmmkOiXL9EF9hGGj97tg-gAYpbvk7UYJM',
    appId: '1:496642683774:ios:6b1f6409d4fdab3273392f',
    messagingSenderId: '496642683774',
    projectId: 'paganini-15f75',
    databaseURL: 'https://paganini-15f75-default-rtdb.firebaseio.com',
    storageBucket: 'paganini-15f75.firebasestorage.app',
    iosBundleId: 'com.example.paganini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmqtzMCrhAG7yCayniNBxeDG6SozWF-aE',
    appId: '1:496642683774:web:c3532882dfaee6ad73392f',
    messagingSenderId: '496642683774',
    projectId: 'paganini-15f75',
    authDomain: 'paganini-15f75.firebaseapp.com',
    databaseURL: 'https://paganini-15f75-default-rtdb.firebaseio.com',
    storageBucket: 'paganini-15f75.firebasestorage.app',
  );
}
